# -*- coding: utf-8 -*-
"""Tarea NeutralFarm Parte Gitub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kh-5mJI3tyWc91d0cLPmz02bSLWnl420
"""

# Montar Google Drive para guardar y acceder a los archivos del proyecto
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# Entrar a la carpeta del proyecto en Google Drive
# %cd "/content/drive/MyDrive/neutral-farming-om"

# Listar todos los archivos que contiene la carpeta
!ls -R

# Configurar identidad de GitHub
!git config --global user.email "pedroeyanezmel531@gmail.com"
!git config --global user.name "p1y1m"

# Inicializar git en la carpeta del proyecto
!git init

# Conectar el repositorio remoto de GitHub
!git remote add origin https://github.com/p1y1m/Codes.git

# Commented out IPython magic to ensure Python compatibility.
# Salir de cualquier repo mal inicializado y limpiarlo
# %cd /content
!rm -rf .git

# Commented out IPython magic to ensure Python compatibility.
# Entrar a la carpeta del proyecto en Drive
# %cd "/content/drive/MyDrive/Pedro Yanez - neutral-farming-om"

# Inicializar git en la carpeta del proyecto y configurar identidad
!git init
!git config --global user.email "pedroeyanezmel531@gmail.com"
!git config --global user.name "p1y1m"

# Conectar el remoto de GitHub (recrear si ya existía)
!git remote remove origin 2>/dev/null || true
!git remote add origin https://github.com/p1y1m/Codes.git

# Commented out IPython magic to ensure Python compatibility.
# # Crear .gitignore para evitar archivos de sistema que rompen el add
# %%bash
# cat > .gitignore << 'EOF'
# .ipynb_checkpoints/
# __pycache__/
# *.gdoc
# *.gsheet
# *.gslides
# *.tmp
# *.log
# .DS_Store
# drive/
# sample_data/
# EOF
#

# Agregar archivos, hacer commit y subir al remoto
!git add .
!git status
!git commit -m "Initial commit - Neutral Farming project"
!git branch -M main
!git push -u origin main

# Generar el PAT en GitHub

# Ir a GitHub tokens
#Tokens (classic).

#Hacer clic en Generate new token (classic).

#Poner un nombre (ej: colab-push), seleccionar repo y poner una expiración

#Copiar el token generado (empieza con ghp_...).

# Configurar identidad de GitHub
!git config --global user.email "pedroeyanezmel531@gmail.com"
!git config --global user.name "p1y1m"

# Eliminar remoto anterior si existe
!git remote remove origin || true

# Conectar al nuevo repositorio usando el PAT directamente
!git remote add origin https://#INSERTAR-TOKEN-PAT@github.com/p1y1m/Tarea-Neutral-Farm.git

# Cambiar la rama a main
!git branch -M main

# Subir el proyecto al nuevo repositorio
!git push -u origin main